name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting (sonarqube)
          fetch-depth: 0

      # Use JDK 17 instead of 11
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run unit tests and generate JaCoCo report
        run: ./gradlew lintDebug testDebugUnitTest jacocoTestDebugUnitTestReport

      # Use 'sonar' instead of deprecated 'sonarqube'
      - name: SonarQube analysis
        run: ./gradlew sonar
